server:
  port: 8002

spring:
  activemq:
    broker-url: tcp://192.168.30.101:61616
    user: ryun
    password: ryun@broker
    in-memory: false
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000

